# I'm installing a knitro mock library to check if the package compiles. 
# Since knitro is a commercial product, I don't think it's a good idea for
# me to install their actual library on travis. The mock library contains 
# the same functions as the real knitro library, yet it just returns 
# meaningless nonsense. Unfortunately that means that I have turn off unit
# testing on travis by setting the environmental variable KNITRO_MOCK=1.
language: c
branches:
  only:
  - master
env:
  global:
  - BOOTSTRAP_LATEX=1 BOOTSTRAP_PANDOC=1 KNITRO=~/knitro-mock-library KNITRO_MOCK=1 LD_LIBRARY_PATH=~/knitro-mock-library/lib
sudo: required
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
- curl -OL http://raw.github.com/jtilly/knitro-mock-library/master/install-knitro-mock.sh
- chmod 755 ./install-knitro-mock.sh
- "./install-knitro-mock.sh"
install:
- mkdir ~/.R
- "./travis-tool.sh install_deps"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
