language: c
branches:
  only:
  - master
env:
  global: 
  - secure: asy8jcyjLUAHVMZoiIFGQnDZeEDFjoq1K48cRsPBwphDVrYm63qJ4Ls5bmWOLOMVxP/G4VOtG8NQAFA0zwRXroFpr2KawU8iC3JxtdYcld+hfkuH4j4cNnpkK2pODmA+BvL65ikideRzkwoand9o+UhFtkjvivYY+tXejpB+sEtSbhT3CjT0Q+GdFV+hylAGTV1etYVxaXoL4yacKwLXnh/dLOW1H7Zg1HginIeGzlIGsTPjNnJ4tKZ/NTUO2HE9y44hnlVX6wrURPH4Mn+/VwDiVVqM+c9yvFJ5GpgK3qgv8VtyM5eJEryZvksMjsUtw4EpXuUO1jiihfQV3M9BaAzMgWLcMZdGYH6CraZdIOdzl4jMoGI2s1Ugs2hc/i01a+tnLlfqoo8CjWL3t4U3usOe3uKbkqKNWO2axU2GEmGV8srYUx7gonJvXchn8RJOBMZGrqfEdNtdFTpU39d2hk5O5P+eGVa114uUp9FDaWhFATzMZJij9TJgXieigoLuobVXcpLIiEc9Dgx6Wh8EQ33NIlSXapQT1NZ8n13iwKBsqbE8pgHzhZDOLkebAK2PoboEys66v3xs3DI4ARAauY+MQxbpzxE8uAeeBuCkTaUABQXEY7uSxv7mZk7JjtBJxvOKE4GqXSDLIZNSSpbQrg5LkQ/+wSsiQORU2bWUeEk=
  - BOOTSTRAP_LATEX=1 BOOTSTRAP_PANDOC=1
sudo: required
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
- curl -OL http://raw.github.com/jtilly/knitro-mock-library/master/install-knitro-mock.sh
- chmod 755 ./install-knitro-mock.sh
- "./install-knitro-mock.sh"
- export KNITRO=~/knitro-mock-library
- export KNITRO_MOCK=1
- export LD_LIBRARY_PATH=~/knitro-mock-library/lib
install:
- mkdir ~/.R
- "./travis-tool.sh install_deps"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
- export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
- Rscript -e "install.packages('rmarkdown', repos='http://cran.rstudio.com')"
- R CMD Rd2pdf ${TRAVIS_BUILD_DIR} -o ${TRAVIS_BUILD_DIR}/${REPO_NAME}.pdf --no-preview
  --no-index --force --batch
- cd ${TRAVIS_BUILD_DIR}
- cd ..
- git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
- cd gh-pages
- git config user.name "Jan Tilly"
- git config user.email "jantilly@gmail.com"
- git checkout gh-pages
- git pull origin gh-pages
- mv -f ${TRAVIS_BUILD_DIR}/${REPO_NAME}.pdf .
- git add *.pdf
- git commit -m "Automatic Travis update of PDF documentation"
- git push origin gh-pages
