language: c
branches:
  only:
  - master
env:
  global:
  	- BOOTSTRAP_LATEX=1 BOOTSTRAP_PANDOC=1
    - secure: gMzf4NU0/gme8B3bsT2k22dfQ14tQ/dJgNazWu1wCXfX+5qm/B4h6JXVkwtPYoB+ZXpEJ4obucmWZjHddJVsDJjXq9WJB/BF3jCEtvkJKls4pgpjv9ue2tGC6mOyLwjpBcFJBgXHWRsqMTK45MyZ+B2mBWBROpi7k4Et7FJ7OXMTeLCQI8MUQp41n922/tDOYPF6ZIhf4j9KSd67upcf2eiH7Dzj6FAdTK8Nas3qpGG1LmdFnFbE+R8e13zpQGkcW+LJx1K0K94xGDrmE7rgVoOYTxJyBdEtJdx9BttfqElLbEzV9Crjm4uofm223l7OmYNCDJdGQbijwAIYXpd/PZHbycrVfVNz8WheW0mQAHCb5OTCvxPc6j0Av3Mo7V81L+7WupKjtA6kV3w4LHKD9+1ub8g/G+eDuzknuxGddx5ucxsn4DPV8zIQjnDJW+7C7govC0m1ps8JJ/fZygBVBB6CpIm3r/tUFEd7mRVgfdl/2MJSM7G8CIB0p24nbo3dV1/tu8/15EMtAm7WQyVpg7bdbfxAf6GiiM7h04w/nYGYNeZnuM9NAV6p1cUcvQaOcE+xd3JFRvoRFZcJDfmRjBQFi3lOPj7+3Y1u50otf5aGF3ZMGckK3VWtDeUHP6+Ty7j4ug+hUY9DfrUJAyIxE2XNN+ybZGEjNbQEoE7gBlI=  
sudo: required
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
- curl -OL http://raw.github.com/jtilly/knitro-mock-library/master/install-knitro-mock.sh
- chmod 755 ./install-knitro-mock.sh
- "./install-knitro-mock.sh"
- export KNITRO=~/knitro-mock-library
- export KNITRO_MOCK=1
- export LD_LIBRARY_PATH=~/knitro-mock-library/lib
install:
- mkdir ~/.R
- "./travis-tool.sh install_deps"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- Rscript -e 'library(covr);coveralls()'
- export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
- Rscript -e "install.packages('rmarkdown', repos='http://cran.rstudio.com')"
- R CMD Rd2pdf ${TRAVIS_BUILD_DIR} -o ${TRAVIS_BUILD_DIR}/${REPO_NAME}.pdf --no-preview --no-index --force --batch
- cd ${TRAVIS_BUILD_DIR}
- cd ..
- git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
- cd gh-pages
- git config user.name "Jan Tilly"
- git config user.email "jantilly@gmail.com"
- git checkout gh-pages
- git pull origin gh-pages
- mv -f ${TRAVIS_BUILD_DIR}/${REPO_NAME}.pdf .
- git add *.pdf
- git commit -m "Automatic Travis update of PDF documentation"
- git push origin gh-pages
notifications:
  email:
    on_success: change
    on_failure: change
