# .travis.yml
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
branches:
  only:
    - master
sudo: required
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - curl -OL http://raw.github.com/jtilly/knitro-mock-library/master/install-knitro-mock.sh
  - chmod 755 ./install-knitro-mock.sh
  - ./install_knitro-mock.sh
  - export KNITRO=~/knitro-mock-library
  - export LD_LIBRARY_PATH=~/knitro-mock-library/lib
install:
  - mkdir ~/.R
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

#after_success:
#  - Rscript -e 'library(covr);coveralls()'
