// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// knitroCpp
NumericVector knitroCpp(List fcts, NumericVector startValues, int num_equality_constraints, int num_inequality_constraints, int nnzJ, NumericVector RjacIndexCons, NumericVector RjacIndexVars, NumericVector ub, NumericVector lb, CharacterVector optionsFile);
RcppExport SEXP knitroR_knitroCpp(SEXP fctsSEXP, SEXP startValuesSEXP, SEXP num_equality_constraintsSEXP, SEXP num_inequality_constraintsSEXP, SEXP nnzJSEXP, SEXP RjacIndexConsSEXP, SEXP RjacIndexVarsSEXP, SEXP ubSEXP, SEXP lbSEXP, SEXP optionsFileSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type fcts(fctsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type startValues(startValuesSEXP );
        Rcpp::traits::input_parameter< int >::type num_equality_constraints(num_equality_constraintsSEXP );
        Rcpp::traits::input_parameter< int >::type num_inequality_constraints(num_inequality_constraintsSEXP );
        Rcpp::traits::input_parameter< int >::type nnzJ(nnzJSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type RjacIndexCons(RjacIndexConsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type RjacIndexVars(RjacIndexVarsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type ub(ubSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lb(lbSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type optionsFile(optionsFileSEXP );
        NumericVector __result = knitroCpp(fcts, startValues, num_equality_constraints, num_inequality_constraints, nnzJ, RjacIndexCons, RjacIndexVars, ub, lb, optionsFile);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
