# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knitroCpp <- function(fcts, startValues, m, nnzJ, RjacIndexCons, RjacIndexVars, options, optionsFile) {
    .Call('knitroR_knitroCpp', PACKAGE = 'knitroR', fcts, startValues, m, nnzJ, RjacIndexCons, RjacIndexVars, options, optionsFile)
}

