# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knitroCon <- function(fcts, startValues, m, optionsFile) {
    .Call('knitroR_knitroCon', PACKAGE = 'knitroR', fcts, startValues, m, optionsFile)
}

knitroUnc <- function(fcts, startValues, optionsFile) {
    .Call('knitroR_knitroUnc', PACKAGE = 'knitroR', fcts, startValues, optionsFile)
}

